import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/shared/theme-provider";
import Sidebar from "@/components/sections/side-bar";
import { InvoiceFormSheet } from "@/components/sections/form-modal";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const generateInvoiceNumber = () => {
  return Math.random().toString(36).substring(2, 8).toUpperCase();
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${leagueSpartan.variable} h-full antialiased`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex flex-col lg:flex-row">
            <Sidebar />
            <InvoiceFormSheet createInvoiceNumber={generateInvoiceNumber()} />
            <main className="p-6 mx-auto w-full lg:w-[800px]">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
